### ISSUE TITLE
Show all tx statuses in wallet history like in explorer

### ISSUE THREAD

**Issue by ILayZ** [josemmo/iotawebwallet#1]
Few suggestions from user-side.
1. Show all tx statuses in wallet history like in explorer.
TheTangle.org:
![default](https://user-images.githubusercontent.com/23453629/36266369-53f1812e-1282-11e8-9e08-20058ce049e7.png)
IotaWebWallet.com:
![default](https://user-images.githubusercontent.com/23453629/36266395-621e764e-1282-11e8-985d-6400e3691ea5.png)

**Comment by josemmo** [comment]
Added in v1.0.3, now it looks like this:

![reattached](https://user-images.githubusercontent.com/4470267/38768524-88a70eca-3ff5-11e8-9644-8cafc4f36927.png)
