### ISSUE TITLE
Make auto-connect to another node, if current failed.

### ISSUE THREAD

**Issue by ILayZ** [josemmo/iotawebwallet#3]
Like in this project: [iota-transaction-spammer-webapp](https://github.com/pRizz/iota-transaction-spammer-webapp)
![default](https://user-images.githubusercontent.com/23453629/36266486-9a6bb1a6-1282-11e8-894c-17cb1a3a43bd.png)

**Comment by josemmo** [comment]
IOTA Web Wallet already has a fallback system which triggers when fetching info from a wallet.

If I'm not mistaken, what iota-transaction-spammer-webapp does is distribute the commands being sent to The Tangle through multiple IOTA nodes at the same time.

But, and here's the thing, IOTA Web Wallet uses iota.lib.js – which the spammer app doesn't – thus relying on the methods and functionality provided by this library.
If IWW were to implement load balancing, first it should be implemented in iota.lib.js.
