### ISSUE TITLE
Can't select any wallet

### ISSUE THREAD

**Issue by ILayZ** [josemmo/iotawebwallet#5]
Windows 7 64-bit (WoW64)

Chrome 64.0.3282.167 (Official), (64 bit)
Firefox Quantum 59.0b10 (64 bit)
Opera 51.0:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 OPR/51.0.2830.34

**Comment by josemmo** [comment]
Probably has something to do with an AdBlock extension preventing crypto.js from loading.

Does the issue still happen?

**Comment by ILayZ** [comment]
I turned off Adblock for iotawebwallet.com . Will see if it helps.
This issue happens sometimes and disappear as well.

2018-02-24 13:23 GMT+03:00 josemmo <notifications@github.com>:

**Comment by josemmo** [comment]
Closing this issue _for now_ because of inactivity and lack of information to reproduce it.
